### ISSUE TITLE
DeprecationError: Deprecated on 2023-08-16: `f.call(...)` is deprecated. It has been renamed to `f.remote_gen(...)`

### ISSUE THREAD

**Issue by tleyden** [modal-labs/doppel-bot#5]
I ran `modal run src.finetune --user="<user>"` and got this error:

```
Beginning scrape for <user> in ...
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/src/scrape.py", line 168, in scrape
    channel_ids = list(get_channel_ids.call(bot_token))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/combined_types.py", line 24, in __call__
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 398, in f_wrapped
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 1158, in call
    deprecation_error(
  File "/pkg/modal/exception.py", line 96, in deprecation_error
    raise DeprecationError(f"Deprecated on {deprecated_on}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: `f.call(...)` is deprecated. It has been renamed to `f.remote_gen(...)`
Beginning scrape for <user> in ...
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/src/scrape.py", line 168, in scrape
    channel_ids = list(get_channel_ids.call(bot_token))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/combined_types.py", line 24, in __call__
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 398, in f_wrapped
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 1158, in call
    deprecation_error(
  File "/pkg/modal/exception.py", line 96, in deprecation_error
    raise DeprecationError(f"Deprecated on {deprecated_on}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: `f.call(...)` is deprecated. It has been renamed to `f.remote_gen(...)`
Beginning scrape for <user> in ...
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/src/scrape.py", line 168, in scrape
    channel_ids = list(get_channel_ids.call(bot_token))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/combined_types.py", line 24, in __call__
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 398, in f_wrapped
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 1158, in call
    deprecation_error(
  File "/pkg/modal/exception.py", line 96, in deprecation_error
    raise DeprecationError(f"Deprecated on {deprecated_on}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: `f.call(...)` is deprecated. It has been renamed to `f.remote_gen(...)`
Beginning scrape for <user> in ...
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/src/scrape.py", line 168, in scrape
    channel_ids = list(get_channel_ids.call(bot_token))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/combined_types.py", line 24, in __call__
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/synchronizer.py", line 398, in f_wrapped
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 1158, in call
    deprecation_error(
  File "/pkg/modal/exception.py", line 96, in deprecation_error
    raise DeprecationError(f"Deprecated on {deprecated_on}: {msg}")
modal.exception.DeprecationError: Deprecated on 2023-08-16: `f.call(...)` is deprecated. It has been renamed to `f.remote_gen(...)`
```

**Comment by tleyden** [comment]
I changed the calls to:

```
    channel_ids = list(get_channel_ids.remote_gen(bot_token))
    users = get_user_id_map.remote_gen(bot_token)
```

and now I'm getting a new error:

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/src/scrape.py", line 173, in scrape
    for pairs in get_question_response_pairs.map(
  File "/pkg/synchronicity/synchronizer.py", line 323, in _run_generator_sync
    raise uc_exc.exc from None
  File "/pkg/modal/object.py", line 382, in wrapped
    async for item in method(self, *args, **kwargs):
  File "/pkg/modal/functions.py", line 1074, in map
    async for item in self._map(input_stream, order_outputs, return_exceptions, kwargs):
  File "/pkg/modal/functions.py", line 978, in _map
    async for item in _map_invocation(
  File "/pkg/modal/functions.py", line 479, in _map_invocation
    async for response in streamer:
  File "/usr/local/lib/python3.11/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
             ^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 344, in drain_input_generator
    async for item in streamer:
  File "/usr/local/lib/python3.11/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiostream/stream/create.py", line 85, in call
    yield await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 337, in create_input
    item = await _create_input(arg, kwargs, client, idx=idx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/functions.py", line 158, in _create_input
    args_serialized = serialize((args, kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_serialization.py", line 52, in serialize
    Pickler(buf).dump(obj)
  File "/usr/local/lib/python3.11/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'generator' object
```

**Comment by tleyden** [comment]
Here's a fix: https://github.com/modal-labs/doppel-bot/pull/6
